# permissions for end users to view additionalscrapeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: additionalscrapeconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prometheus-static-target
    app.kubernetes.io/part-of: prometheus-static-target
    app.kubernetes.io/managed-by: kustomize
  name: additionalscrapeconfig-viewer-role
rules:
- apiGroups:
  - prometheus-static-target.kube-stager.io
  resources:
  - additionalscrapeconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prometheus-static-target.kube-stager.io
  resources:
  - additionalscrapeconfigs/status
  verbs:
  - get
