# permissions for end users to edit scrapejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: scrapejob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: prometheus-static-target
    app.kubernetes.io/part-of: prometheus-static-target
    app.kubernetes.io/managed-by: kustomize
  name: scrapejob-editor-role
rules:
- apiGroups:
  - prometheus-static-target.kube-stager.io
  resources:
  - scrapejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - prometheus-static-target.kube-stager.io
  resources:
  - scrapejobs/status
  verbs:
  - get
