name: Release pipeline

on:
  release:
    types: [ published ]
  push:
    branches: [ github-actions ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

#    - name: Run tests
#      run: make test

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        file: ./Dockerfile
##        platforms: linux/arm64,linux/amd64
#        platforms: linux/amd64
#        push: true
#        outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Kube-stager prometheus-static-target operator
#        tags: |
#          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


    - name: Release
      run: make docker-buildx VERSION=$GITHUB_REF_NAME

    - name: List image
      run: |
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        docker image ls ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

